### ISSUE TITLE
Can i delete and regenerate files in StreamingAssets

### ISSUE THREAD

**Issue by takaaptech** [RickJiangShu/ConfigManager#2]
Hi,
Your lib is awesome! I can load data from SerializableSet but I do not know what is the file in StreamingAssets. Are they auto generate? If I modify data in input CSV, do I have to modify the file in StreamingAssets again?
Sometimes, Press output do not re generating file (Unity 2017.1.0f3 mac)
![screen shot 2017-07-18 at 9 05 49 am](https://user-images.githubusercontent.com/6276251/28297517-93d650bc-6b98-11e7-9497-f62a9eb54ff3.png)

**Comment by RickJiangShu** [comment]
Thank you for your feedback

1.SerializableSet is UnityEngine.ScriptableObject in StreamAssets.StreamAssets is not auto generate.You need set assetBundleName and BuildAssetBundles.

![image](https://user-images.githubusercontent.com/29089955/28302713-a29dddda-6bc1-11e7-9b34-23528022a5e4.png)

2.If you modify data, You need press output, It's generate new SerializableSet, then you need set assetBundleName and BuildAssetBundles.

3.I check it in mac later

**Comment by takaaptech** [comment]
Ah ok for some reasons the Source Folder change to other location. After fix it back to Assets/Config, it works well! Thank you!
Now i can understand if i change file data in Assets/Config folder, I can Clear output and then press Output to regenerate SerializableSet and C# file again.

But I still unsure about files in StreamingAssets folder (i mean config, config.ab ... files). Can i delete and then generate it again? Or is it by our plugin default? 

And if i press Test Build on my mac, it errors because BuildTarget targetPlatform = BuildTarget.StandaloneWindows; 
After change to StandaloneOSXUniversal
It show warning 

No AssetBundle has been set for this build.
UnityEditor.BuildPipeline:BuildAssetBundles(String, BuildAssetBundleOptions, BuildTarget)
TestBuild:Build() (at Assets/Example/Editor/TestBuild.cs:27)

So as i see maybe StreamingAssets not refresh again.

Thank you very much!

**Comment by RickJiangShu** [comment]
A.you can delete all files in StreamAssetsFolder.

No AssetBundle has been build.Because SerializableSet is a new file.

Please follow the steps below to try:
1.delete all files in StreamAssetsFolder
2.press Output
3.select SerializableSet.asset ,click "new" and set assetBundleName to "config.ab"
![image](https://user-images.githubusercontent.com/29089955/28312630-627afc9a-6be6-11e7-94f5-33db995033c6.png)
4.click "Test/Build" generate "config.ab"

B.This plugin no support auto generate assetbundle, because everyone's loading strategy is different. But Thank you for making me realize that there is a need for optimization.

**Comment by RickJiangShu** [comment]
A.you can delete all files in StreamAssetsFolder.
No AssetBundle has been build.Because SerializableSet is a new file.
Please follow the steps below to try:
1.delete all files in StreamAssets Folder
2.press Output
3.select SerializableSet.asset ,click "new" and set assetBundleName to "config.ab"
4.click "Test/Build" generate "config.ab"
B.This plugin no support auto generate assetbundle, because everyone's loading strategy is different. But Thank you for making me realize that there is a need for optimization.



rickjiangshu@gmail.com
 
From: takaaptech
Date: 2017-07-18 17:50
To: RickJiangShu/ConfigManager
CC: Rick; Comment
Subject: Re: [RickJiangShu/ConfigManager] Can i delete and regenerate files in StreamingAssets (#2)
Ah ok for some reasons the Source Folder change to other location. After fix it back to Assets/Config, it works well! Thank you!
Now i can understand if i change file data in Assets/Config folder, I can Clear output and then press Output to regenerate SerializableSet and C# file again.
But I still unsure about files in StreamingAssets folder (i mean config, config.ab ... files). Can i delete and then generate it again? Or is it by our plugin default?
And if i press Test Build on my mac, it errors because BuildTarget targetPlatform = BuildTarget.StandaloneWindows;
After change to StandaloneOSXUniversal
It show warning
No AssetBundle has been set for this build.
UnityEditor.BuildPipeline:BuildAssetBundles(String, BuildAssetBundleOptions, BuildTarget)
TestBuild:Build() (at Assets/Example/Editor/TestBuild.cs:27)
So as i see maybe StreamingAssets not refresh again.
Thank you very much!

**Comment by takaaptech** [comment]
Thank so much, follow your comment i can now delete and create files in StreamingAssets folder!
I just a newbie in Unity, can you explain what is difference and main purpose when Loading by Resource or by AssetBunble? Real life example is great!
Thank so much!

**Comment by RickJiangShu** [comment]
AssetBundle can runtime updates resources **from a server**, it's called "hot update".But Resource.Load can't do it.

example:Your game is released, but you found that your one config file is wrong.Now you can modify the config file, build AssetBundle, and replace the wrong config's AssetBundle on the server .

**Comment by RickJiangShu** [comment]
AssetBundle can runtime updates resources from a server, it's called "hot update".
But Resource.Load can't do it.
example:Your game is released, but you found that your one config file is wrong.Now you can modify the config file, build AssetBundle, and replace the wrong config's AssetBundle on the server .



rickjiangshu@gmail.com
 
From: takaaptech
Date: 2017-07-20 10:14
To: RickJiangShu/ConfigManager
CC: Rick; Comment
Subject: Re: [RickJiangShu/ConfigManager] Can i delete and regenerate files in StreamingAssets (#2)
Thank so much, follow your comment i can now delete and create files in StreamingAssets folder!
I just a newbie in Unity, can you explain what is difference and main purpose when Loading by Resource or by AssetBunble? Real life example is great!
Thank so much!

**Comment by takaaptech** [comment]
Oh! Awesome! Can you recommend plugin for easier "hot update" feature? Some github repo would be great!

**Comment by RickJiangShu** [comment]
I'm sorry,I don't have used plugin of "hot update".

But i recommand you can look at the officical tutorial:
https://unity3d.com/cn/learn/tutorials/topics/scripting/assetbundles-and-assetbundle-manager 

―

**Comment by takaaptech** [comment]
Thank so much! @RickJiangShu
